name: Deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
          GIT_CONFIG_NAME: Projektitekt
          GIT_CONFIG_EMAIL: bot@projektitekt.de
          single-commit: true
